name: khata_management
description: "this project is created for shuab bhai for his gass business"
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.23.1
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  printing: ^5.14.2
  pdf: ^3.11.3
  intl: ^0.20.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.5.0
  open_filex: ^4.7.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.23.1
  build_runner: ^2.4.15
  msix: ^3.16.9

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - assets/fonts/JameelNooriNastaleeq.ttf
  fonts:
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf
    - family: JameelNooriNastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf

msix_config:
  display_name: Virtual Manager
  publisher_display_name: Saari Technologies
  identity_name: com.saaritech.khata.management
  msix_version: 1.1.0.0
  capabilities: internetClient
